### ISSUE TITLE
tSnowflakeOutput UPSERT file uploading fails when profile path contains space

### ISSUE THREAD

**Issue by swiffer** [Talend/components#1102]
Jobs are failing if the profile path contains a space in the user name. At least that's what i think as i cannot see another difference when running a job from different computers and failing on one.

Exception in component tSnowflakeOutput_1 (JOB_NAME)
java.io.IOException: net.snowflake.client.loader.Loader$ConnectionError: File could not be uploaded to remote stage after retrying 6 times:

**Comment by pteyssier** [comment]
Hello,
We use jira as our bugtracker, I've created https://jira.talendforge.org/browse/TDI-40214 base on your information, feel free to add a comment there so i can set you as reporter of the issue.

**Comment by swiffer** [comment]
@pteyssier don't know how to comment in Jira but this is fixed in snowflakes jdbc driver release 3.6.2 ;)
