### ISSUE TITLE
Links are broken in the documentation

### ISSUE THREAD

**Issue by gunicsba** [Talend/components#1159]
Hello,

I wanted to read the docs and understand how this new component creator works / behaves. However the wiki page links are broken (giving me 404).

Most of the links on the below page are broken.
https://github.com/Talend/components/wiki/4.-Component-Definition 

Regards,
   Balázs

**Comment by gonchar-ivan** [comment]
Hello, thank you for the issue found.

I have updated this wiki page.
https://github.com/Talend/components/wiki/4.-Component-Definition

Regards,
Ivan
