### ISSUE TITLE
Talend Components newbuild.talend.com dependencies

### ISSUE THREAD

**Issue by tperroin** [Talend/components#1449]
Hi,

We are using Talend 6.2.1 since almost 2 years and we have created a specific component for our ERP. Actually we need to upgrade some dependencies but we are facing issues accessing your : http://newbuild.talend.com:8081 nexus server.

So we tried to change this URL by http://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceSnapshot/ but it seems that there is still some dependencies pointed at _newbuild.talend.com_.

We are in the 0.13.0 version of components-parent.

The maven archetype doesn't work too...

`mvn archetype:generate -DarchetypeGroupId=org.talend.components -DarchetypeArtifactId=components-api-archetypes -DarchetypeVersion=0.13.0 -DarchetypeRepository=http://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceSnapshot/`

Can you take a look at it?

Thank you

**Comment by berengerrollin** [comment]
Did you take a look on transitive dependencies ?
:D

**Comment by tperroin** [comment]
Closing this issue due to workaround
