### ISSUE TITLE
Sink class and WriteOperation error

### ISSUE THREAD

**Issue by tperroin** [Talend/components#427]
Hello,

I'm trying to develop a set of components for our company for better integration with our ERP.

I already managed to create 3 components. One for connection, one for consumption and the last one to close the connection.

I would like to create a Talend Job like that :

[![Talend M3 api component](https://i.goopics.net/02Qy.png)](https://goopics.net/i/02Qy)

It works well for my tM3ApiConnection and tM3ApiClose, but not for the tM3ApiConsumer component.

The goal is to provide input parameters (from a delimited file in this example) to the tM3ApiConsumer component. This one must call a specific API form our ERP and return errors and/or results.

For the tM3ApiConsumer I have created tM3ApiConsumerDefinition and Properties. The definition implements an OutputComponentDefinition and set a Sink runtime class (M3ApiSink).

Here are my M3ApiSink, M3ApiWriter and M3ApiWriteOperation classes :

```java
public class M3ApiSink extends M3ApiSourceOrSink implements Sink {

    public M3ApiSink() {
    }

    @Override
    public ValidationResult validate(RuntimeContainer runtimeContainer) {
        ValidationResult validationResult = super.validate(runtimeContainer);

        if (validationResult.getStatus() != ValidationResult.Result.ERROR) {
            if (!(properties instanceof tM3ApiConsumerProperties)) {
                return new ValidationResult().setStatus(ValidationResult.Result.ERROR)
                        .setMessage("properties should be of type :" + tM3ApiConsumerProperties.class.getCanonicalName());
            }
        }

        return validationResult;
    }

    @Override
    public WriteOperation<?> createWriteOperation() {
        return new M3ApiWriteOperation(this);
    }

    @Override
    public List<NamedThing> getSchemaNames(RuntimeContainer runtimeContainer) throws IOException {
        return Collections.emptyList();
    }
}
```

```java
public class M3ApiWriter implements Writer<Result> {

    private static final Logger LOG = LoggerFactory.getLogger(M3ApiWriter.class);

    private final M3ApiSink sink;

    private final WriteOperation writeOperation;

    private IndexedRecordConverter<Object, ? extends IndexedRecord> factory;

    private Result result;

    public M3ApiWriter(WriteOperation writeOperation) {
        LOG.debug("M3ApiWriter :: constructor");
        this.writeOperation = writeOperation;
        sink = (M3ApiSink) writeOperation.getSink();
    }

    @Override
    public void open(String uid) throws IOException {
        LOG.debug("M3ApiWriter :: open");
    }

    @Override
    public void write(Object o) throws IOException {
        LOG.debug("M3ApiWriter :: write");
    }

    @Override
    public Result close() throws IOException {
        LOG.debug("M3ApiWriter :: close");
        LOG.debug("M3ApiWriter :: close :: result " + result);
        return new Result();
    }

    @Override
    public WriteOperation<Result> getWriteOperation() {
        LOG.debug("M3ApiWriter :: getWriteOperation :: writeoperation: " + writeOperation);
        return writeOperation;
    }
}
```

```java
public class M3ApiWriteOperation implements WriteOperation<Result> {

    private static final Logger LOG = LoggerFactory.getLogger(M3ApiWriteOperation.class);

    private final M3ApiSink sink;

    public M3ApiWriteOperation(M3ApiSink sink) {
        LOG.debug("M3ApiWriteOperation :: constructor");
        this.sink = sink;
    }

    @Override
    public void initialize(RuntimeContainer runtimeContainer) {
        LOG.debug("M3ApiWriteOperation :: initialize");
    }

    @Override
    public Map<String, Object> finalize(Iterable<Result> iterable, RuntimeContainer runtimeContainer) {
        LOG.debug("M3ApiWriteOperation :: finalize");
        return Result.accumulateAndReturnMap(iterable);
    }

    @Override
    public Writer<Result> createWriter(RuntimeContainer runtimeContainer) {
        LOG.debug("M3ApiWriteOperation :: createWriter");
        return new M3ApiWriter(this);
    }

    @Override
    public M3ApiSink getSink() {
        LOG.debug("M3ApiWriteOperation :: getSink :: " + this.sink);
        return this.sink;
    }
}
```

My problem is that when I run the Talend Job, I have a NullPointerException talking about Avro :
`
Exception in component tM3ApiConsumer_1
java.lang.NullPointerException
	at org.talend.daikon.avro.AvroUtils.isIncludeAllFields(AvroUtils.java:200)
	at org.talend.daikon.di.DiIncomingSchemaEnforcer.<init>(DiIncomingSchemaEnforcer.java:85)
	at tperroin.test_0_1.test.tFileInputDelimited_3Process(test.java:1200)
	at tperroin.test_0_1.test.tM3ApiConnection_1Process(test.java:453)
	at tperroin.test_0_1.test.runJobInTOS(test.java:2550)
	at tperroin.test_0_1.test.main(test.java:2384)
[FATAL]: tperroin.test_0_1.test - tM3ApiConsumer_1 null
`

Without any concrete examples I have some troubles to find how to resolve this error. The M3ApiWriter is never called. I would like to read the content of my incoming schema to call the API.

Have you some advice ? Am I using the right solution ?

Thank you to share that new way to develop components !

PS : We are in the 6.2.1 version of Talend

**Comment by RyanSkraba** [comment]
Hello!  It is very impressive to see a third party using the API, and thanks so much for your early feedback!

You've probably noticed that we're iterating quickly on the project, so there are many changes between minor versions.  The branch for Talend 6.2.x is `maintenance/0.13`.  When we judge that we have a stable API, we'll bump the version to `1.0.0` and the component development experience should be much more agreeable, more rigorously backwards compatible and with better documentation!

In the meantime, I'm happy to answer any questions and any feedback is welcome :)

For the components framework, the "gold standard" for exchanging data between components is the Avro IndexedRecord.  We're working on enabling other data containers (see the doc at https://github.com/Talend/components/wiki/6.-Component-Runtime#receiving-data).  In the studio, the incoming object is guaranteed to be an IndexedRecord and you can simple cast the incoming value.

The error that you are getting is a bit odd -- it looks like the Studio is not translating the columns that you specified for the connection into a correct Avro Schema for your record!  This is very strange.  Would it be possible to share the contents of the schema defined on the connection `row3` in your above job?

Once again, welcome to the project!  All my best, Ryan

**Comment by tperroin** [comment]
Hello,

It's nice to hear that you are active and you want to create a 1.0.0 version ! 

For us, this new way to create components is much nicer that the old one. I'm working on the `maintenance/0.13` already. And I think I will have a lot of questions during my developments. 

You were right about my connection schema for the `row3`. It's works for now, I can get each row values from the main flux in my `Writer` class. I'm working now with Avro IndexedRecord.

I have another question about connectors. I tried to create a component that provide two output schemas, like the tESBConsumer.

[![tESBConsumer](https://i.goopics.net/N92R.png)](https://goopics.net/i/N92R)

Is that a way to do that in the current API ?

I already tried to provide schemas in my properties like that :

```java
@Override
protected Set<PropertyPathConnector> getAllSchemaPropertiesConnectors(boolean b) {
      HashSet<PropertyPathConnector> connectors = new HashSet<>();

     if (b) {
        connectors.add(inputConnector);
        connectors.add(outputConnector);
    } else {
        connectors.add(inputConnector);
    }
    return connectors;
}
```

I'm not sure about this solution. Any advice ?

Thank you !

**Comment by undx** [comment]
Hello Thibault,

Yes, you can do it like that.
In a case of an incoming and outgoing component : 
```java
protected transient PropertyPathConnector MAIN_CONNECTOR = new PropertyPathConnector(Connector.MAIN_NAME, "schema");
protected transient PropertyPathConnector FLOW_CONNECTOR = new PropertyPathConnector(Connector.MAIN_NAME, "schemaFlow");
protected transient PropertyPathConnector REJECT_CONNECTOR = new PropertyPathConnector(Connector.REJECT_NAME, "schemaReject");

@Override
public Set<PropertyPathConnector> getAllSchemaPropertiesConnectors(boolean isOutputConnection) {
    HashSet<PropertyPathConnector> connectors = new HashSet<>();
    if (isOutputConnection) {
        connectors.add(FLOW_CONNECTOR);
        connectors.add(REJECT_CONNECTOR);
    } else {
        connectors.add(MAIN_CONNECTOR);
    }
    return connectors;
}
```
Also, have a look at the [WriterWithFeedback](https://github.com/Talend/components/blob/master/components-api/src/main/java/org/talend/components/api/component/runtime/WriterWithFeedback.java) interface.

**Comment by RyanSkraba** [comment]
Thanks @undx! This is the correct technique for input components, and `WriterWithFeedback` is the correct technique for output components.  If you have feedback or suggestions on managing multiple output connections in your components, please don't hesitate to contact!

**Comment by tperroin** [comment]
Thanks a lot @undx and @RyanSkraba ! I understand better the output possibilities of the writer component.

Now, I try to provide an output schema from the ERP Api's response. I keep you in touch about my progresses.

**Comment by tperroin** [comment]
I make a few progresses in my development. However I'm stuck with output functions `getSuccessfulWrites` and `getRejectedWrites`.

In my `write` function, I have this code :

```java
String recordTransaction = mvx.getTransaction();
String repTransaction = recordTransaction.substring(0, 3);
IndexedRecord successRecord = new GenericData.Record(schemaFlow);
while ("REP".equals(repTransaction)) {
    for (Schema.Field field : schemaFlow.getFields()) {
        successRecord.put(field.pos(), mvx.mvxGetField(field.name()));
    }
    successfulWrites.add(successRecord);
    recordTransaction = mvx.mvxRecv();
    repTransaction = recordTransaction.substring(0, 3);
}
```
It creates a record with all my needs but the output main row doesn't iterate. Maybe it's the behavior that Talend aims to do. 

![M3 apiconsumer output](https://cloud.githubusercontent.com/assets/1137581/22021664/c8c9d2bc-dcbe-11e6-8185-fd538b18968c.png)

I would like an iterable output after my tM3ApiConsumer (`row3`) which provides multiple records as : `{"CONO": "100", "PUNO": "2441038"}`. Those records are already created in my `write` function.

The `successfulWrites` function is :

```java
@Override
public List<IndexedRecord> getSuccessfulWrites() {
    return Collections.unmodifiableList(this.successfulWrites);
}
```

Am I doing it right ? Do I have to modify my output schema or my schema properties ?

Thank you for your help !

**Comment by sgandon** [comment]
I think the same issue has been resolved in the Snowflake component, can you have a look at https://github.com/Talend/components/blob/master/components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java .
Is that what you are looking for ?

**Comment by tperroin** [comment]
hum, I don't really understand this class, sorry...

Actually, I'm looking for a way to create multiple output schemes from one input row.

For example :

The input schema :

Field A | Field B
---- | ----
100 | 500

the target output schema (it will create an output for each lines) :

Field A | Field B | Field C
---- | ---- | ----
100 | 500 | 200
100 | 500 | 210
100 | 500 | 220

So, for now I have a list of `IndexedRecord`. It doesn't insert data in my output schema and my list is not iterated.

My problem is clearer ? Have you more information about it ?

Thank you !

**Comment by undx** [comment]
Hello @tperroin,
You're clear in your explainations !
What do you get if you do some integration tests (ie not in the studio) ?
Is the `successfulWrites` list correct ?
Maybe a studio issue...

**Comment by tperroin** [comment]
Hello @undx 

I was not able to create integration tests... I'm not aware of how to do them...

However, my `successfulWrites` seems to be OK :

```java
getSuccessfulWrites [{"CONO": "100", "PUNO": "2441034", "PNLI": "10"}, {"CONO": "100", "PUNO": "2441034", "PNLI": "10"}]
getSuccessfulWrites class class java.util.ArrayList
getSuccessfulWrites element class org.apache.avro.generic.GenericData$Record
```

The first line is the list content, the second the class of that list and the third the class of an element of that list.

How do we set values of a schema from the `write` function ?

**Comment by undx** [comment]
Perhaps, I didn't understood correctly but in your debug  dump you've 2 rows and the screenshot shows 2 output rows on the `row3`.  Your number of rows seems to fit...
If your `schemaFlow` is the **same** as your input schema, you'll have the same output as your incoming flow.
Your code:
```java
  for (Schema.Field field : schemaFlow.getFields()) {
        successRecord.put(field.pos(), mvx.mvxGetField(field.name()));
    }
```
Is it that the problem or am I missing something? 

I think (I may be wrong...) that you should generate an `IndexedRecord` for each of your output in the loop:

```java
String recordTransaction = mvx.getTransaction();
String repTransaction = recordTransaction.substring(0, 3);
IndexedRecord successRecord;
while ("REP".equals(repTransaction)) {
    successRecord = new GenericData.Record(schemaFlow);
    for (Schema.Field field : schemaFlow.getFields()) {
        successRecord.put(field.pos(), mvx.mvxGetField(field.name()));
    }
    successfulWrites.add(successRecord);
    recordTransaction = mvx.mvxRecv();
    repTransaction = recordTransaction.substring(0, 3);
}

**Comment by tperroin** [comment]
Ok, my bad !

In fact, My input file contains 2 rows with values:

CONO: 100; PUNO: 2441038
CONO: 100; PUNO: 2441034

So, for each line of this `tFileInputDelimited` I want to call the `tM3ApiConsumer`. This component will call, for each line, a specific API from our ERP with a socket. That socket will return one or more elements by API call. And that's why you saw 2 rows in my debug trace. Here a screenshot with only one row in my file:

![image](https://cloud.githubusercontent.com/assets/1137581/22027926/b6c0e6d4-dcd5-11e6-93f8-3a3a8298569e.png)

So the code here aims to but all responses of ONE API call:

```java
for (Schema.Field field : schemaFlow.getFields()) {
    successRecord.put(field.pos(), mvx.mvxGetField(field.name()));
}
```

After that it will be great if I could iterate throw those results and create a schema for all responses. That's why I was talking about an iterable row (Talend meanings) for the `row3`.

Is it clearer ?

**Comment by undx** [comment]
Ok, that's clear ! ;-)
So your Writer class seems to be good according to the debug trace. 
What does the `tLogRow_2` outputs ?
``` CONO: 100; PUNO: 2441034``` ?

**Comment by tperroin** [comment]
Nice to hear !

The `tLogRow_2` output is:

CONO | PUNO | PNLI
------- | ------- | -----
100 |2441038|0   

But here is not the right behavior for me. I would more than one line in that output and the value PNLI should be valued to `10` :/

**Comment by undx** [comment]
Obviously, it can be a Studio issue...

Let's see what the guys say...

**Comment by gonchar-ivan** [comment]
Hello guys!

Despite getSuccessfulWrites() and getRejectedWrites() return Iterable, Studio uses only first element from that Iterable. Yes, it is a kind of a bug. 
(Actually, not a bug. Rather a feature, which is not implemented yet in new API. However, seems it was available in old API)

For now, we support only one outgoing record per each incoming record.

**Comment by tperroin** [comment]
Oh... Too bad to hear that !

For components, IMO, it will be nice to get back the `iterable` schema/connector.

But for now, is there another solution for my problem? 
And do you support backward compatibility? 
Which version do you use for your tests for now?

Thank you a lot for help! It's great to have support!

**Comment by gonchar-ivan** [comment]
However I want to understand the logic of your component better.
Because maybe there is an option to implement it as another type of component and it will work.
I'll try to explain what I mean.
There are following types of components: Input, Output, Transform, Standalone

Input is an entry point. It reads some data from data storage.
Output is a destination point. It is the last component in data process. It writes data to some data storage.
Transform component receives some data, process it somehow and passes to next components.
It should support different configurations:
1 input - 1 output
1 input - many output
many input - 1 output
but new API doesn't support it yet (
Stanalone component doesn't deal with data, but it may do some work. (e.g. create/remove table on DB storage)

In your case your consumer component could be either Input or Transform. It depend on what cono and puno is. If it is rather not data, but settings, which are used to make API call, then I would say your component is Input. And cono and puno should be properties. 
(In this case you may use iterate flow, which will allow you to start M3ApiConsumer component several times with different settings (cono & puno). Your job design will be something like: 
tFileDelimited -- iterate --> tM3ApiConsumer -- flow --> tLogRow. 
thus TFileDelimited provides settings for each run of tM3ApiConsumer  -> tLogRow subjob)

But if cono & puno is data itself and purpose of tM3ApiConsumer is to enrich incoming data by adding one more field, then it is Transform component (which is not fully supported yet).

Ivan

**Comment by gonchar-ivan** [comment]
Sorry, I didn't understand this point:
"For components, IMO, it will be nice to get back the iterable schema/connector."

"But for now, is there another solution for my problem?"
Yes, there is. You may try to implement your component as Input and use iterate flow (a.k.a connection).
Described above.

"And do you support backward compatibility?"
Yes, we do.

"Which version do you use for your tests for now?"
new API (a.k.a TCOMP, a.k.a Component Framework) is developed in parallel with Studio.
It means:
Studio 6.2.1 is compatible with 0.13.1 TCOMP
6.3.0 -> 0.15.0 TCOMP
6.3.1 -> 0.16.0 TCOMP
The latest TCOMP released is 0.17.0
We use latest release for our tests

**Comment by tperroin** [comment]
Wow! Thank you to get so deep in details for my problem guys!

My component `tM3ApiConsumer` is for now an Output component. My first idea when I started to develop a component was to create an Input one. 

But to call an API we have to provide a kind of schema with for example CONO and PUNO. It's parameters of a function if you prefer. So, when you talked about settings, where do you set those settings in the Studio? They have to be dynamic depending of the API selected in our case.

My design thinking was to create a flux like: one input to multiple output. The input will be a schema given by the API and the output a different one given by the API too.

If I'm right, with Talend we could do:
tFileInputDelimited --> tM3ApiConsumer --> iterate --> log each output of my API in schemes

Do you understand my logic better? Is it possible right now, with the current API state?

Thanks again!

**Comment by gonchar-ivan** [comment]
I suggest you to add CONO and PUNO as _user properties_ (which are implemented in ComponentProperties class) Then you will have something like:

Programme ___
API ___
Schema
Schema
Schema
Cono ___
Puno ___

**Comment by tperroin** [comment]
We can't do that with an input schema? 
Because some of our APIs had more than 30 parameters in input...

And it will be easier for us to work with schemes.

**Comment by gonchar-ivan** [comment]
"We can't do that with an input schema?"
Currently, it is not possible, because "1 input -> many output" is not supported now.
Technically it should be possible in the future.
However, as for me it breaks a concept a little. Parameters for API call is rather settings, than data.
Flows(connections) is supposed to transfer data and properties are designed for settings/parameters.
(Actually, it is an open question for me whether it is acceptable to transfer settings/parameters via flows)

**Comment by tperroin** [comment]
Hum...

So in Talend how can I set dynamically data in settings/parameters? With globalMap?

In design time, we don't know the value of CONO or PUNO for example. Does an input component can get incoming information too btw?

I know it's a lot of questions... But we are new customers of Talend and we expect a lot of your product!

**Comment by tperroin** [comment]
I close this issue and create a new one because I think I have to create a Input component with a Reader and not an Output one.
