### ISSUE TITLE
Schemes management in component

### ISSUE THREAD

**Issue by tperroin** [Talend/components#431]
Hello,

It's me again. I come back to you to get some information about schemes.

My objective is to have 3 schemes in my component as the tESBConsumer.

I would like to add forms like that (it's from the tESBConsumer) :
[![ESB schemes](https://i.goopics.net/vbge.png)](https://goopics.net/i/vbge)

So for now I just managed to add 3 different schemes in my form. I was not able to rename fields in the form, and define schemes as input, output flow and output error.

![M3 form schemes](https://cloud.githubusercontent.com/assets/1137581/21978603/8dff39d0-dbdb-11e6-90de-9b7187169f6e.png)

So, I would like the same behavior that the tESBConsumer :

- How can I set a schema as a input flow and another as an output one ?
- How can I rename the schema text in form of the editor ?

I don't know if you are ok with my explanations. It's not that easy for me to explain it !

Thanks again, I really like the way to develop components with this new API.

**Comment by gonchar-ivan** [comment]
Hello, Thibault Perroin!

I'll try to help you.

1) Component type.
As I understand you are developing transformation component (a.k.a intermediate). It can both consume and emit data. For now TCOMP (Component Framework) has no full support for development Transform component. However, you may try to implement it as WriterWithFeedback

https://github.com/Talend/components/blob/master/components-api/src/main/java/org/talend/components/api/component/runtime/WriterWithFeedback.java

getSuccessfulWrites() may be used for response data (commonly we put single data instance in Iterable. But in some special cases it may contain several data)
getRejectedWrites() may be used for fault data

**Comment by gonchar-ivan** [comment]
2. Schemas.
There are 2 kinds of schema:
a. design - user specifies it in UI to tell component what to expect.
(So you are doing it correctly. User of your component can edit or just view schema related to each flow (a.k.a connection) )
b. runtime - it is real runtime data schema. This schema goes together with data
(IndexedRecord should contain it)
Usually Runtime schema should be the same as design (component should produce data in the same way as user required)

However, sometimes user can't configure what should be returned by data storage. E.g. error message record may have fixed format (e.g. it is a record with 2 columns: int errorCode, string errorMessage)
In this case component may set default schema value, which is not editable. It is used just to show user what will be returned.

Here is example:
https://github.com/Talend/components/blob/master/components-jira/src/main/java/org/talend/components/jira/tjirainput/TJiraInputProperties.java#L131-L140

**Comment by gonchar-ivan** [comment]
3. Translation (i18n)

I hope following links will help you:
first is property definition (batchSize property) in ComponentProperties class:
https://github.com/Talend/components/blob/master/components-jira/src/main/java/org/talend/components/jira/tjirainput/TJiraInputProperties.java#L49

second is display message (translation) for this property:
https://github.com/Talend/components/blob/master/components-jira/src/main/resources/org/talend/components/jira/tjirainput/messages.properties#L6

So in your case you should have something like in messages.properties file:
property.inputSchema.displayName=Input Schema
property.responseSchema.displayName=Response Schema
property.faultSchema.displayName=Fault Schema  (maybe rejectSchema. As I know we call it Reject)

where "inputSchema" is corresponding field name in your ComponentProperties class

Also you need another .properties file for French translation. 
(However, you may try French labels directly in messages.properties)

**Comment by gonchar-ivan** [comment]
4. Schemas usage at runtime.
As I described above your component likely will implement WriterWithFeedback interface.
So, environment Platform (Studio) will pass some data in the form IndexedRecord to your
Writer.write(Object) method (Writer is superinterface of WriterWithFeedback). Your component should know how to handle(parse) incoming IndexedRecords. It may use Input schema, which is specified by user in UI (design schema) for this purpose.

Response schema (Output) specified by user should be attached to outgoing data (IndexedRecords returned by component in response on getSuccessfulWrites() call)

The same for Fault schema (Reject schema). It should be set in IndexedRecords returned by getRejectedWrites()

**Comment by tperroin** [comment]
Wow ! Thanks for all those information @gonchar-ivan !

I had completely forgotten about `*.properties` files.

With all those details I think I can create schemes dynamically, corresponding to our ERP APIs.
I'm working on a better `Writer` now.

**Comment by gonchar-ivan** [comment]
Cool! Thank you too for using our new API.

Don't hesitate to ask more questions. 

Also we will be very grateful for any feedback about API: is it convenient, what is good, what is not good, what should be improved etc.

**Comment by tperroin** [comment]
Oops !

I have some troubles with `.properties` files. I have a ComponentProperties class for my component with those properties :

```java
protected transient PropertyPathConnector inputSchema = new PropertyPathConnector(Connector.MAIN_NAME, "schema");
protected transient PropertyPathConnector outputSchema = new PropertyPathConnector(Connector.MAIN_NAME, "schemaFlow");
protected transient PropertyPathConnector rejectSchema = new PropertyPathConnector(Connector.REJECT_NAME, "schemaReject");

public SchemaProperties schema = new SchemaProperties("schema");
public SchemaProperties schemaFlow = new SchemaProperties("schemaFlow");
public SchemaProperties schemaReject = new SchemaProperties("schemaReject");
```

So, to set a name for those properties, I have added properties in `messages.properties`

```properties
property.schema.displayName=Schema input
property.schemaFlow.displayName=Schema output
property.schemaReject.displayName=Schema error
```

Unfortunately, it doesn't seems to work :

![Schemes components](https://cloud.githubusercontent.com/assets/1137581/21985762/8ffde3e6-dbfc-11e6-8eeb-e7b64a908b42.png)

For information, I'm in the `maintenance\0.13` branch. Have you already had this problem ?

**Comment by tperroin** [comment]
@gonchar-ivan the API is good for now. I think I will create a issue about my feelings after the development of the component. 

But for now, it's nice to use it. The API is good, more documentation will be great but I understand it will be better in `1.0` version.

**Comment by gonchar-ivan** [comment]
hm...
Do you check your component in Studio?
Maybe this could help:
https://github.com/Talend/components/wiki/Quickstart-using-Maven-Archetype#step-8-testing-the-component-in-talend-studio

4. Delete the org.eclipse.* folders from the <Studio root folder>/configuration directory. (each time you redeploy component you are developing)

You have "Schéma" (French schema). It should come from somewhere. Maybe previous value in .properties file. That's why I suggest to clean cache (org.eclipse.* folders).
When i18n values can't be found then you see "property.schema.displayName" as label in Studio. But you see "Schéma".

Another my idea:
try to switch to another language in Studio.

**Comment by tperroin** [comment]
@gonchar-ivan,

Yes, I try my component in the Talend Studio. I clear every time all `org.eclipse.*`folders and replace my jar bundle.

I also tried to change the Studio language in English and modify my `messages.properties`, but I'm stuck with the same behavior. 

Maybe, I'm not doing the right think in my `setupLayout` function.

Here is the part form my schemes :

```java
Form schemaForm = schema.getForm(Form.REFERENCE);
mainForm.addRow(schemaForm);
Form schemaFlowForm = schemaFlow.getForm(Form.REFERENCE);
mainForm.addRow(schemaFlowForm);
Form schemaRejectForm = schemaReject.getForm(Form.REFERENCE);
mainForm.addRow(schemaRejectForm);
```

It's ok for now, the problem is just about cosmetic. 

Have you another idea ?

Thanks

**Comment by gonchar-ivan** [comment]
Hi

Your setupLayout() method is ok.

I'm sorry. I have no more reasonable ideas...
However, word "Schéma" should come from somewhere. Could you try to find which file inside your component project contains string "Schéma"

Ivan

**Comment by tperroin** [comment]
Hello,

It's working now. I was putting my `messages.properties` in the wrong directory...

My bad !

Thank you
