### ISSUE TITLE
Java links in project's wiki are broken

### ISSUE THREAD

**Issue by sim51** [Talend/components#918]
Hi,

I just let you know that a lot of links (to some java class)  in the project's wiki are broken.
As an example, just try the first link of this page https://github.com/Talend/components/wiki/5.-Component-Properties.

Cheers.

**Comment by gonchar-ivan** [comment]
Hi, 
Thanks. 
I fixed links on https://github.com/Talend/components/wiki/5.-Component-Properties page.
We will need to check and fix links on other pages.
